name: build.yml
on: [pull_request]

jobs:
  macos-brew:
    name: macOS (brew)
    runs-on: macos-latest
    steps:
      # ... macOS build steps ...

  build-linux:
    strategy:
      matrix:
        os: [debian-11, ubuntu-22.04]
    name: ${{ matrix.os }}
    runs-on: ubuntu-latest # (or a custom runner)
    steps:
      # ... Linux build steps ...
      
  test-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-24.04]
    name: Ubuntu 24.04 (tests)
    runs-on: ubuntu-24.04
    steps:
      # ... Test execution steps ...
